### ISSUE TITLE
Does this need to be updated to use reCAPTCHA v2?

### ISSUE THREAD

**Issue by dnmfarrell** [Sidnet/p5-Dancer2-Plugin-reCAPTCHA#2]
v1 reCAPTCHA stopped working on my site last month (perltricks.com) because Google stopped supporting it. 

See https://metacpan.org/pod/Mojolicious::Plugin::ReCAPTCHAv2 for an example.of a V2 reCAPTCHA implementation.

**Comment by oiami** [comment]
Hi, thanks for your suggestion! reCAPTCHA v1 is still working on our site. Anyway, we also planed to update to reCAPTCHA V2. Now the code in code review. Hopefully we can release it by the end of this month.

**Comment by oiami** [comment]
The new version of Dancer2::Plugin::reCAPTCHA with reCaptcha V2 is released and live on CPAN now! :)

**Comment by dnmfarrell** [comment]
Woohoo, great job!
